### PR TITLE
Add scim.write by default

### PR DESCRIPTION
**Pull request by longnguyen11288**
Allow admin users to create admin users by default

### CODE REVIEW

**Comment by fhanik** [comment]
it's a sensible default, the scope uaa.admin allows the user to modify itself and add the scope. This prevents that extra step.

**Comment by longnguyen11288** [comment]
Is preventing this extra step a problem?

**Comment by fhanik** [comment]
Sorry for the confusion. My comment implies that this PR is a sensible default. That is enhances the usability.

**Comment by drnic** [comment]
Thanks mate

**Comment by longnguyen11288** [comment]
Any updates on merging this in?

**Comment by dieucao** [comment]
It's been merged. This will be in the next cf-release.

**Comment by longnguyen11288** [comment]
I'm confused why it said closed but not merged?

**Comment by drnic** [comment]
Awesome thanks.

**Comment by dieucao** [comment]
@longnguyen11288 I'm not sure.
You can see that it's merged here: https://github.com/cloudfoundry/cf-release/commit/3e70ee57a2ffac43fa04e6f60fb9aa6b7cfe94fc

**Comment by longnguyen11288** [comment]
Ahh I see it. Sorry was looking at master not develop thanks @dieucao

**Pull request closed without merging**
