### PR TITLE
Use new, proper buildpack BOSH release names

### PR DESCRIPTION
**Pull request by RochesterinNYC**
- Buildpack BOSH release names no longer contain the -release suffix
- https://www.pivotaltracker.com/story/show/130040305

Warning: As per discussion at https://cloudfoundry.slack.com/archives/release-integration/p1476888802001242, this commit breaks cf-release for anyone using cf-release as a monolithic release from the :develop branch while the Buildpacks team bumps the buildpack BOSH release submodules in cf-release.

These buildpack BOSH release submodules will be bumped by the buildpacks Concourse infrastructure. Buildpacks team anticipate disruption will be brief. While this particular commit will never be usable by itself, the :develop branch will become stable after submodule bumps are complete.

Signed-off-by: Jacques Chester <jchester@pivotal.io>

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
https://www.pivotaltracker.com/story/show/130040305 is blocked on this PR.

**Comment by sclevine** [comment]
@Amit-PivotalLabs mind merging this soon? Our cf-release pipeline is blocked on this.

**Comment by Amit-PivotalLabs** [comment]
@RochesterinNYC @sclevine if you have run the manifest generation unit tests, this looks good to me.  You can actually just commit this directly, no need to wait for PR merge.  If you commit directly, please delete your branch after the fact.

Thanks,
Amit

**Comment by RochesterinNYC** [comment]
Gotcha. Yup, we've run the manifest generation unit tests. We'll merge and delete the branch.

**Pull request merged**
