### PR TITLE
Adding optional config to HAProxy for logging, buffer size, and stats socket.

### PR DESCRIPTION
**Pull request by amhuber**
This pull request was discussed in two group threads:

https://groups.google.com/a/cloudfoundry.org/forum/?utm_medium=email&utm_source=footer#!msg/vcap-dev/70MYeQbDnQc/mmSRWfKM0a0J
https://groups.google.com/a/cloudfoundry.org/forum/?utm_medium=email&utm_source=footer#!msg/vcap-dev/iWO7QDqt0AM/RqQslk_QYcYJ

This will also close two current trackers:

https://www.pivotaltracker.com/n/projects/966314/stories/88373146
https://www.pivotaltracker.com/n/projects/966314/stories/87802174

Changes:

* Add optional config to log HAProxy to /var/vcap/sys/log via rsyslog configuration (default is /var/log/syslog)
  * This requires some permissions changes to /var/vcap/sys and /var/vcap/sys/log so rsyslog can traverse the folders
* Add optional config to enable a stats socket for HAProxy
* Add optional config to enable the "dontlognull" setting
  * Upstream load balancers that use TCP checks to HAProxy result in larger numbers of "null" requests that get added to the logs
  * Enabling this option will disable logging of the null requests, but that will also eliminate logging of port scanning requests or anything else that hits HAProxy without actually transmitting data
* Add configuration for the buffer size, with the default value being the HAProxy default
  * Increasing the buffer size is required to handle requests with large query strings or cookies

The new configuration is optional and no manifest changes are required, and if the new settings aren't added to the manifest then the new config will be identical to the old config.

In addition, the "http-server-close" option was removed. This was required in older HAProxy versions in order to make the X-Forwarded-Proto header work correctly, but it resulted in disabling server-side keep-alive.  The new HAProxy version does not require this entry and removing it should result in a (potentially significant) performance improvement as HAProxy can now keep a pool of connections to the routers open instead of initiating new connections for every request.

Aaron Huber
Intel Corporation

### CODE REVIEW

**Comment by amhuber** [comment]
Note that based on the forum discussion the desire is to remove the permissions changes and add syslog to the vcap group:

https://www.pivotaltracker.com/n/projects/956238/stories/89303062

This will require a stemcell update, so there are two options:

1) Pull in this change as-is for now with the permisisons changes, and then I'll submit a new one once the syslog changes are made to remove the 2 chmod commands.
2) Wait until the stemcell change is made and then I'll add a commit to remove the chmod commands.

Aaron Huber
Intel Corporation

**Comment by zaksoup** [comment]
Thanks @amhuber! We're just going to go with option 2 and stick this pull in our backlog until the bosh changes are made. We'll pull it in as soon as that happens!

@zaksoup + @crhino CF Runtime Team

**Comment by amhuber** [comment]
OK, I'll pull out the two chmod commands and add a commit, then this will be ready to pull in once the BOSH changes are ready.

**Comment by zaksoup** [comment]
Sounds good. We'll ping you when it gets pulled in.

**Comment by dieucao** [comment]
@amhuber Looks like bosh made changes for this in stemcell 2915.  I'll move this into the backlog, probably a few weeks out.

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824330](https://www.pivotaltracker.com/story/show/99824330) Adding optional config to HAProxy for logging, buffer size, and stats socket.


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by Amit-PivotalLabs** [comment]
@amhuber Sorry for the long delay.  This story has been prioritized now in the new Routing team's backlog:

https://www.pivotaltracker.com/story/show/89303250

**Comment by shalako** [comment]
Hello @amhuber  couple of requests:

Please update the property name `ha_proxy.buffer_size` to include the units of measure. Looking at http://www.haproxy.org/download/1.4/doc/configuration.txt (`tune.bufsize`), I believe this is bytes. So our property should be`ha_proxy.buffer_size_bytes`

Also, how does one connect to the stats socket? On a particular port? Would you ever want to change this port?

Thank you

**Comment by amhuber** [comment]
You can connect to the stats socket using either socat or nc (examples at http://www.mgoff.in/2010/07/14/haproxy-gathering-stats-using-socat/ and https://tech.fawk.eu/111/), so there is no port involved, just the socket file.

Have you already done any work on resolving the conflicts since this is is based off such an old config?  If not then it's probably easier for me to rebase this against a current release and re-test it submit a new pull request, assuming you would be able to pull it in more quickly so it doesn't get out of sync again?  That way I can also confirm that the change to the stemcell for the syslog permissions is working correctly.

Let me know and if that works for you I'll close this and submit a new request next week.

Aaron

**Comment by shalako** [comment]
Hello @amhuber, I just realized how long ago your submitted this. Sorry about that! We'll take care of the property name change.

**Comment by amhuber** [comment]
Works for me, thanks!

**Comment by Amit-PivotalLabs** [comment]
@shalako @amhuber Have whatever desired property name changes been done?  If so, can this PR be closed?

**Comment by shalako** [comment]
The commit made it to release-candidate: https://github.com/cloudfoundry/cf-release/commit/ead532949b697c4a837e499075fcc8a3805f432e

Closing

**Pull request closed without merging**
