### PR TITLE
Add minimum_candidate_stagers to manifest template

### PR DESCRIPTION
**Pull request by ScarletTanager**
[#119362989]

Signed-off-by: Dan Lavine <dlavine@us.ibm.com>

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Any reason this default of 5 isn't in the job spec rather than the manifest template @ScarletTanager @DanLavine?

**Comment by DanLavine** [comment]
@Amit-PivotalLabs,

There is already a default of 5 in the job spec. However it seems kind of odd when looking at a manifest that was generated and this field having a nil value. We are just following the same scheme where the value of nil does not make much sense. (i.e. staging_disk_limit_mb)

/cc @ScarletTanager

**Comment by Amit-PivotalLabs** [comment]
Sorry, I don't quite understand.  Is there some functional reason why the default value from the spec needs to be duplicated in the template (which is something we strongly try to avoid), or is it just that the manifest looks odd?

**Comment by DanLavine** [comment]
@Amit-PivotalLabs 

It is just to make the generated manifest more readable. There is no technical reason that the values need to be duplicated. We are just being consistent in how these descriptive values are in both places.

**Comment by Amit-PivotalLabs** [comment]
We strongly avoid duplicating default values in job specs and the manifest templates.  If we are consistently doing this in other places in the manifest templates, we should remove those as well.  How the manifest reads is less important at this time.  Thanks for the PR, but will close it out for now.

**Pull request closed without merging**
