### PR TITLE
Stop using deprecated UAA properties for bosh lite manifest

### PR DESCRIPTION
**Pull request by Gerg**
`jwt.signing_key` and `jwt.verification_key` are deprecated as per the [uaa spec](https://github.com/cloudfoundry/uaa-release/blob/40952b504f7faed64f8a79187124bf5038fbddb0/jobs/uaa/spec#L356-L359)

Tracker story: https://www.pivotaltracker.com/story/show/133151385

Signed-off-by: Jonathan Berkhahn jaberkha@us.ibm.com

### CODE REVIEW

**Comment by Gerg** [comment]
Hold off on merging this until we sort out what is up with UAA segfaults.

**Comment by dsabeti** [comment]
@gerg Let me know when y'all are ready for me to prioritize this.

**Comment by dsabeti** [comment]
Hey @Gerg, any update on this?

**Comment by Gerg** [comment]
Not sure when it will be ready. @SocalNick has details, but I think we are waiting on a new version of Ruby before we bring these manifest changes back.

**Comment by SocalNick** [comment]
We can also fix this bug instead of waiting for Ruby version: https://www.pivotaltracker.com/story/show/133947925

**Comment by dsabeti** [comment]
@SocalNick, once that story is finished, should we merge this PR?

**Comment by SocalNick** [comment]
@dsabeti that story and this one: https://www.pivotaltracker.com/story/show/134190789

**Comment by ChunyiLyu** [comment]
The changes are already in rc. We think the PR could be closed.

**Pull request closed without merging**
