### PR TITLE
bosh-lite: update consul certificates

### PR DESCRIPTION
**Pull request by pommi**
The previous certificate expired:
> Issuer: CN = consulCA
> Validity
>     Not Before: Aug  8 00:11:37 2015 GMT
>     Not After : Aug  8 00:11:38 2017 GMT

The new certs are generated via ./scripts/generate-consul-certs
and are valid for another 2 years:
> Issuer: CN = consulCA
> Validity
>     Not Before: Aug  8 13:08:23 2017 GMT
>     Not After : Aug  8 13:08:23 2019 GMT

### CODE REVIEW

**Comment by pommi** [comment]
Maybe it's interesting to mention that I hit this issue while deploying and then I noticed that this certificate was expired.
```
Started updating instance consul_z1 > consul_z1/e4c7e37d-b310-427b-b694-683c192f4b52 (0) (canary). Failed: 'consul_z1/0 (e4c7e37d-b310-427b-b694-683c192f4b52)' is not running after update. Review logs for failed jobs: consul_agent (00:03:53)

Error 400007: 'consul_z1/0 (e4c7e37d-b310-427b-b694-683c192f4b52)' is not running after update. Review logs for failed jobs: consul_agent
```

Then the logs of consul_agent showed me:
```
2017/08/08 10:35:06 [INFO] serf: Received list-keys query
2017/08/08 10:35:06 [ERR] http: Request GET /v1/operator/keyring, error: rpc error: failed to get conn: x509: certificate has expired or is not yet valid from=127.0.0.1:38198
```

**Comment by dsabeti** [comment]
Thanks for catching this @pommi. I've prioritized the story to get merged soon.

**Comment by staylor14** [comment]
@pommi can you re-submit the pull request against our develop branch, please?

**Comment by jaresty** [comment]
@pommi We changed the base for you -- nevermind!  (cc: @staylor14)

**Comment by jaresty** [comment]
Hey @pommi we ran into a test failure as a result of this PR.  We've fixed it, but for future reference it would help us if you could please run `scripts/test` before creating a pull request on `cf-release`.    The test fixture update was done [in this commit](https://github.com/cloudfoundry/cf-release/commit/4d42ddd044dc24f8ae676561a85e85d445a1f51c).

**Comment by pommi** [comment]
Thanks for merging. I didn't know about `scripts/test`. It would be nice if this was part of your CI, so that a Pull Request is not allowed to be merged until all tests pass.

**Pull request merged**
