### PR TITLE
Change UAA timestamp logging to be rfc3339 compatible

### PR DESCRIPTION
**Pull request by youngm**
This will add timezone information and improve timestamp detection on log servers like Splunk.

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
@mbhave @fhanik @sreetummidi just want to check in, do you see any issue with this PR?  Does anything else depend on the existing log format?

**Comment by sreetummidi** [comment]
Looks good to us

Thanks,
Sree Tummidi
Sr. Product Manager
Identity - Pivotal Cloud Foundry

**Comment by sreetummidi** [comment]
@amitkgupta It actually does have implications on the customers using the existing log format.
If there are SIEM/Log-Collection/Analytics solutions hooked up which expect this format for parsing, they will break.
We should make this a configurable property in the manifest instead so that it can be set to any required format
-Sree

**Comment by Amit-PivotalLabs** [comment]
Thanks @sreetummidi 

@youngm can you make the log format a manifest-configurable property?

**Comment by youngm** [comment]
@Amit-PivotalLabs Sure, I'll update the PR.

**Comment by youngm** [comment]
@Amit-PivotalLabs I've updated the PR to make it optional and I updated varz logging as well.

**Comment by fhanik** [comment]
Wouldn't the smoothest to just expose the pattern? Or is that risky to break the logging?

uaa:
  logging: 
    format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

**Comment by youngm** [comment]
@fhanik I'd be willing to do that also if you want to revert this. I mostly just need timezone specified and rfc3339 seemed to be the standard that includes timezone.

However, I think it would be nice to establish a consistent format for date in logs rather than any format the user wants.  As I find other components not using rfc3339 or a epoch timestamp I plan to submit PRs to those projects as well to help provide some uniformity in this space.

**Pull request merged**
