### PR TITLE
Make Openstack spec fixture stub more realistic [#105805252]

### PR DESCRIPTION
**Pull request by Amit-PivotalLabs**
This is coupled to https://github.com/cloudfoundry/loggregator/pull/98

### CODE REVIEW

**Comment by allomov** [comment]
Hey, @Amit-PivotalLabs!

Are you sure in [this changes](https://github.com/Amit-PivotalLabs/cf-release/blob/fix-openstack-stub/.gitmodules#L63) to `.gitmodules`? From the first view it can cause problems for those, who already have the submodule.

**Comment by Amit-PivotalLabs** [comment]
@allomov sorry, I meant to also say:

**NOTE**: the change to `.gitmodules` should only be used to evaluate the PR, in case you get to this before the loggregator PR is merged.  You can:

1. check this PR out
2. git submodule sync
3. run the tests

But this PR should only be merged after loggregator PR is merged, and the submodule to loggregator is bumped in cf-release, and then `.gitmodules` here should be modified to point back to `cloudfoundry/loggregator`.

**Comment by allomov** [comment]
@Amit-PivotalLabs nice notes, thank you for it.

**Comment by amitkgupta** [comment]
These changes were pulled in manually: https://github.com/cloudfoundry/cf-release/commit/eee7972f8874992fde2486d6636d11d03d59c73b. Closing.

**Pull request closed without merging**
