### PR TITLE
ability to set floating ips for consul

### PR DESCRIPTION
**Pull request by ramonskie**
see https://github.com/cloudfoundry/cf-release/issues/913

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Do tests pass with this change? See https://github.com/cloudfoundry/cf-release/issues/913#issuecomment-189972697

**Comment by ramonskie** [comment]
when i run
```
./scripts/test
```
i get the following error
```
php-buildpack/php_buildpack-cached-v4.3.5.zip
/home/klm21904/Workspace/cf-release/scripts/unused_blobs:26:in `<main>': unhandled exception
```

no idea what the issue is

**Comment by Amit-PivotalLabs** [comment]
Not sure why you're seeing that error.  Can you share the output of:

```
cf-release$ ls blobs/php-buildpack/php_buildpack-cached-v4.3.5.zip
cf-release$ cat src/buildpacks/php-buildpack-release/packages/php-buildpack/spec
```

From the `cf-release` directory, you can run `bundle && bundle exec rspec spec` to check the manifest generation tests alone.

**Comment by ramonskie** [comment]
i found my issue i checked out a the repo and forgot to run the update script.

for now i have some manifest generation errors with aws 
so im going to fix this

**Comment by ramonskie** [comment]
okay i traced the issue and that is to adjust the spec
i don't know if this is something you want..

**Comment by Amit-PivotalLabs** [comment]
Yup, if you're changing the spiff templates, the resulting output of the manifest generation will change as well, so the the files in `spec/fixtures/*/cf-manifest.yml` will need to be updated.  Could you include those changes with your PR?

**Comment by robdimsdale** [comment]
Hi @ramonskie , we've merged the PR into the `develop` branch (this PR was mistakenly made against master), so we're closing this PR.

We also update the the `consul_z2` job for consistency.

Rob && @dsabeti

**Comment by ramonskie** [comment]
:+1:

**Pull request closed without merging**
