### PR TITLE
Use new managed NAT gateway

### PR DESCRIPTION
**Pull request by Infra-Red**
This will simplify minimalistic deployment of Cloud Foundry. New managed NAT gateway can be created and configured with a couple of clicks, instead of launching EC2 NAT instance.

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Thanks @Infra-Red!

I've never walked through these instructions myself, so I'll try it out and make sure the new NAT gateway instructions work with the rest of the existing instructions.  Might take me a little while to get to this.  In the mean time, we'll also wait for your CLA.

**Comment by Amit-PivotalLabs** [comment]
@Infra-Red have you noticed any issues with your NAT Gateway? Some colleagues of mine have reported flakiness, as have some others in general as well: https://forums.aws.amazon.com/thread.jspa?threadID=222925

**Comment by Infra-Red** [comment]
@Amit-PivotalLabs I have not seen such problems and my current installation works as expected, but I do not exclude the possibility of problems with the new service... Also i made some simple tests and didn't faced this issue.

**Comment by Amit-PivotalLabs** [comment]
Got this email from a colleague:

> There's a known issue with the rubygems CDN (Fastly) and the NAT Gateway. Googling with this new information returned the following thread: https://forums.aws.amazon.com/thread.jspa?messageID=696009

> There's a good description of the problem in the response. AWS support has not given a timeline for a fix, so you'll want to avoid the NAT Gateway service for the time being.

Seems like this will make staging ruby apps flaky.

**Pull request closed without merging**
