### PR TITLE
Add cloud_controller_ng_console script to ease debugging of cloud controller

### PR DESCRIPTION
**Pull request by allomov**
Hey, all.

Sometimes to debug problems related to CC I need to put a special script to run CC IRB console for debugging purposes.

I think someone might find it useful.

### CODE REVIEW

**Comment by allomov** [comment]
What are your thought?

**Comment by Amit-PivotalLabs** [comment]
Thanks @allomov 

I will ask the CAPI team to take a look.

/cc @dieucao @zrob

**Comment by zrob** [comment]
Hi @allomov 

There should already be a script at `/var/vcap/jobs/cloud_controller_ng/bin/console` on a bosh deployed cloud controller that will give you an irb session.

Can you give that a try and see if it fits your needs?

Thanks,
@zrob

**Comment by allomov** [comment]
@zrob yes, and template from this PR runs `/var/vcap/jobs/cloud_controller_ng/bin/console` script. Still `console` script needs to have configured environment variables for bundler and path to configuration file. Template from this PR is a shorter way to run this console.

**Comment by youreddy** [comment]
Hi there @allomov, 

We just instantiated a Cloud Foundry from scratch, and were able to bosh ssh into the CC and run the console script without any additional configuration and it worked fine. Could you elaborate on the necessity of all the environment configurations in your script?

Thanks,
@youreddy and @jberkhahn
CF CAPI Team

**Comment by dieucao** [comment]
due to inactivity closing this PR. Please open a new issue or PR if you have any additional questions.

**Pull request closed without merging**
