### PR TITLE
add script to generate manifest from github

### PR DESCRIPTION
**Pull request by jim80net**
This script allows for manifest generation without a checkout of the repo.

It would be used from a wrapper script (an example is provided inline with the code)

Signed-off-by: MKB <mkb@starkandwayne.com>

### CODE REVIEW

**Comment by amitkgupta** [comment]
As of the next final release, there will be no more templates in submodules (see current release-candidate branch, templates directory, for instance).  Given that fact, does this script still serve much of a purpose?

**Comment by jim80net** [comment]
updated PR to reflect that, thanks @amitkgupta. The script would help CloudOps out (and other operators, I imagine), by allowing an operator to generate a manifest without having to have a checkout of cf-release, which would save a bunch of time and downloading.

**Comment by Amit-PivotalLabs** [comment]
@jim80net 

I still see several issues with this PR (some small, some not so small):

1. Comments mention `pivotal-cloudops`
2. There is no test coverage for the script
3. It seems impossible to keep up to date: if I change the names of the templates, there's no way to have a passing test for this script that reflects the current ref until I push the changes up to GitHub first, so I would have to push before the test passes, defeating the purpose
4. There is no cf-lamb.yml; the change that makes the loggregator submodule unnecessary also removes the `cf-lamb.yml` template and includes the relevant templating in the other template files (this is perhaps stark proof of point 3)
5. It leaks the implementation of `generate_deployment_manifest`, basically any logic in that script needs to be duplicated for this script to stay up to date.
6. I'm not sure the point of having this in cf-release itself.

What if you just did:

```
$ git clone --depth=1 --branch ${desired_branch} https://github.com/cloudfoundry/cf-release /tmp/hi-mom
$ cd /tmp/hi-mom && ./scripts/generate_deployment_manifest ${iaas} ${OLD_PWD}/stubs/my-stub.yml
```

As long as you only every need branches or tags (not arbitrary refs) it's pretty fast and much more guaranteed to be up to date.

**Comment by jim80net** [comment]
You're right for all of those points. The workaround provided doesn't work for us, because we do sometimes want arbitrary refs. However, we found a way to do this without injecting things into cf-release: https://gist.github.com/jim80net/9f0a9ca9679f664cca08

Thanks!

**Comment by Amit-PivotalLabs** [comment]
Cool, glad you still found something that worked.

**Pull request closed without merging**
