### PR TITLE
Update cf-infrastructure-bosh-lite.yml

### PR DESCRIPTION
**Pull request by dprotaso**
Update the client secret to be consistent with the client id

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Thanks @dprotaso 

The change itself looks good to me.  Does this pass the unit tests?  If not, do you mind fixing them and resubmitting the PR as a single squashed commit that passes tests.  If it does pass tests, let me know and I'll prioritize for merging.

Best,
Amit

**Comment by dprotaso** [comment]
bacon

**Comment by Amit-PivotalLabs** [comment]
Thanks @dprotaso 

Mind squashing, so it's a single correct commit?

Thanks,
Amit

**Comment by dprotaso** [comment]
The bacon image has two strips - but I'll see what I can do

**Comment by dprotaso** [comment]
single-bacon

**Comment by ChunyiLyu** [comment]
LGTM

**Pull request merged**
