### PR TITLE
Part 1: Upgrade to UAA 2.2.4 (Merged UAA/Login server)

### PR DESCRIPTION
**Pull request by fhanik**
Upgrade to UAA 2.2.4 (Merged UAA/Login server)
This is the first part of a [2 part PR](https://github.com/cloudfoundry/cf-release/pull/621) in order to allow zero downtime.

This PR updates the UAA to v2.0.3 which is hosts both login.<domain> and uaa.<domain>
It register routes
  uaa.<domain>
  login.<domain>
to the same job

It leaves the login job alone, this job will be removed in the next PR

### CODE REVIEW

**Comment by dieucao** [comment]
@fhanik Does this merged UAA/Login server include the latest from Login 1.14?

**Comment by fhanik** [comment]
@dieucao - the 1.14 login server already has been merged and in prod
https://github.com/cloudfoundry/cf-release/pull/604

**Comment by fhanik** [comment]
Closing - obsolete by https://github.com/cloudfoundry/cf-release/pull/621

**Comment by fhanik** [comment]
Incorrectly closed the wrong PR

**Pull request merged**
