### PR TITLE
Remove RC4 from supported SSL ciphers

### PR DESCRIPTION
**Pull request by ian-plosker**
RC4 is no longer considered secure and should not be included in HAProxy's SSL cipher suites

https://community.qualys.com/blogs/securitylabs/2015/04/23/ssl-labs-rc4-deprecation-plan

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
@shalako can you take a look?

Thanks.

**Comment by Amit-PivotalLabs** [comment]
@shalako any update on this PR?

**Comment by shalako** [comment]
Story has been prioritized.

**Comment by crhino** [comment]
Merged as of 270e67bc91f69ffee493ed252e0729949f93b01f

**Pull request closed without merging**
