### PR TITLE
Move statsd-injector job to point to statsd-injector-release

### PR DESCRIPTION
**Pull request by enocom**
Signed-off-by: Sam Nelson <nelsam@pivotal.io>

### CODE REVIEW

**Comment by jaresty** [comment]
Hey @enocom sorry for the late response. There is a merge conflict with this PR, if you could fix the merge conflict, then we'll merge. Thanks!

**Comment by wfernandes** [comment]
@jaresty We fixed the merge conflict. Please verify if all looks good. Thanks.

**Comment by bradylove** [comment]
We have updated the job name to be more sane. Once that has been accepted on our end we will update the PR.

**Comment by bradylove** [comment]
@jaresty The changes we needed to make for statsd-injector have been pushed and are part of this PR.

**Pull request merged**
