### PR TITLE
Fix Docs

### PR DESCRIPTION
**Pull request by timeartist**

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Hi @timeartist 

Were you able to submit the CLA?

Best,
Amit

**Comment by timeartist** [comment]
Yes

**Comment by Amit-PivotalLabs** [comment]
@timeartist Ok, @cfdreddbot didn't work, I'll manually confirm.

**Comment by chipchilders** [comment]
@Amit-PivotalLabs confirmed that we have the CLA

**Comment by Amit-PivotalLabs** [comment]
Great, thanks! Story prioritized.

**Comment by JesseTAlford** [comment]
Thanks for the fix to the readme, Adi! I bet folks tripped on that. Merged.

**Pull request merged**
