### PR TITLE
added Google Compute Engine template

### PR DESCRIPTION
**Pull request by poligraph**
Created Google Compute Engine template and updated generate script.

### CODE REVIEW

**Comment by poligraph** [comment]
@cfdreddbot my organization Altoros already signed CLA, and I don`t need to sign it again.

**Comment by ChunyiLyu** [comment]
@chipchilders, can we get your read on the @cfdreddbot situation here? It looks like @poligraph's membership in Altoros is public, so...

@poligraph, assuming Chip can help clear up this dreddbot situation, we're happy to merge this. There is a caveat; it'll basically be in the same boat as OpenStack currently is, where we're not using manifest generation for this IaaS in our own CI, and can't guarantee that it will work or keep it updated. We will, of course, be happy to continue to accept pull requests.

**Comment by chipchilders** [comment]
@ChunyiLyu @poligraph 

I'll open a bug with toolsmiths. Altoros is listed in the bot's config.

This is OK to merge.

**Comment by chipchilders** [comment]
@poligraph ... the bots check for your publicly displayed GH org memberships. The team responsible for the bot checked the logs, and it didn't show that you were listed as being in the Altoros org. Did you make that public after sending in this PR?

**Comment by chipchilders** [comment]
close/open to bump dreddbot

**Comment by chipchilders** [comment]
close/open to bump dreddbot

**Comment by dsabeti** [comment]
@poligraph Thanks for this PR, and apologies for the delay.

The Release Integration team is focusing its efforts on making [cf-deployment](https://github.com/cloudfoundry/cf-deployment) -- which uses new BOSH features to abstract away configuration based on your cloud provider -- ready for consumption. When it's ready, we're going to deprecate this repo and the manifest generation scripts in it. Far more importantly, though, we don't have the bandwidth to maintain a GCP template in the meantime, and the last thing we want to do is add a template whose functionality we can't guarantee. As such, we don't want to merge this PR in.

On the other hand, I don't want this work to go to waste, and I think many people in the community would benefit from having it made public in meantime. Would you be willing to keep this maintained as a community member? You could put the template in its own repo, with instructions for how use it. You don't even need the `generate_deployment_manifest` script -- you could run this with: 
```
spiff merge \
  cf-release/templates/generic-manifest-mask.yml \
  cf-release/templates/cf.yml \
  cf-gce-template/cf-infrastructure-gce.yml \
  ...
```
To make sure that people in the community see this, feel free to email cf-dev@lists.cloudfoundry.org about the template.

I'm happy to discuss this further, so let me know how this sounds to you. I want this to be available to people to use, and I certainly don't want to deter future contributions. As I said above, my concern here is that it seems unfair to put something in cf-release if we don't guarantee its functionality as time goes on.

**Comment by dsabeti** [comment]
We're actually going through the same thing in another PR, in this case to add an Azure template: https://github.com/cloudfoundry/cf-release/pull/1091

**Comment by dsabeti** [comment]
I wanted to update this PR before officially closing (finally).

There's a doc [here](https://github.com/cloudfoundry/cf-deployment/blob/master/gcp-deployment-guide.md) for deploying CF to GCP. It uses cf-deployment instead of cf-release. I should re-iterate the the repo is still not GA, but we're working to calling it "prod ready" soon.

**Pull request closed without merging**
